# Project information
site_name: "Javier Iparraguirre"
site_description: "Engineer, educator, researcher, and consultant."
site_url: https://javierip.github.io

# Copyright
copyright: "Copyright &copy; Javier Iparraguirre"

nav:
  - About: index.md
  - Publications: publications.md
  - Contact: contact.md

# Configuration
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: deep orange
    accent: indigo

plugins:
  - search:
      lang: en

extra:
  analytics:
    provider: google
    property: G-8ZT4TE5E92
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/javierip
      name: Javier at GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/javieripa
      name: Javier at Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jiparraguirre/
      name: Javier at LinkedIn
